CREATE TABLE IF NOT EXISTS Recipe (
  Id INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
  Name TINYTEXT NOT NULL,
  Description TEXT NOT NULL,
  Ingredients TEXT NOT NULL,
  Directions TEXT NOT NULL,
  Image TEXT,
  DateCreated DATE NOT NULL,
  DateUpdated DATE NOT NULL,
  Categories TINYTEXT,
  CookTime TINYTEXT,
  PrepTime TINYTEXT,
  TotalTime TINYTEXT,
  Yield TINYTEXT,
  Servings TINYTEXT,
  Calories SMALLINT,
  DietaryRestrictions TEXT,
  CHECK(Calories >= 0),
  CHECK(DateUpdated >= DateCreated),
);